name: tfm_env

channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - jupyterlab
  - pip
  - python=3.10
  - pip:
    - huggingface_hub[cli]
    - utilsforecast
    - praxis
    - paxml
    - jax[cpu]==0.4.26
    - einshape
    - scikit-learn
