[tool.poetry]
name = "timesfm"
packages = [
    { include = "*", from = "src" },
]
version = "0.0.1"
description = "Open weights time-series foundation model from Google Research."
authors = [
    "Rajat Sen <senrajat@google.com>",
    "Yichen Zhou <yichenzhou@google.com>",
    "Abhimanyu Das <abhidas@google.com>",
    "Petros Mol <pmol@google.com>",
    "Justin GÃ¼se <guese.justin@gmail.com>",
]
readme = "README.md"
keywords = ["time series", "timesfm", "forecast", "time series model"]
homepage = "https://github.com/google-research/timesfm"
repository = "https://github.com/google-research/timesfm"
classifiers = [
    "Environment :: Console",
    "Framework :: Flake8",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
einshape = ">=1.0.0"
numpy = ">=1.26.4"
pandas = ">=2.1.4"
paxml = "1.4.0"
jax = "0.4.26"
jaxlib = "0.4.26"
utilsforecast = "^0.1.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
